version: '3.3'
# This compose file is for development environment. For production use only Dockerfile

services:
  app:
    env_file:
      - .env
    build: .
    command: bash -c "yarn dev-start"
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    links:
      - database
    depends_on:
      - database
  database:
    env_file:
      - .db.env
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: {}
